
export const ADD = 'ADD'
export const INCREMENT = 'INCREMENT'
export const MESSAGE = 'MESSAGE'
export const CHANGEACTIVE ="CHANGEACTIVE"


//后面可以删掉
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
